var masterOBJ = {
  TSLA: {
    symbol: "TSLA",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  AAPL: {
    symbol: "AAPL",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  INTC: {
    symbol: "INTC",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  NFLX: {
    symbol: "NFLX",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  NVDA: {
    symbol: "NVDA",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  META: {
    symbol: "META",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  GOOGL: {
    symbol: "GOOGL",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  AMZN: {
    symbol: "AMZN",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
"BINANCE:BTCUSDT": {
  symbol: "BINANCE:BTCUSDT",
  LTP: 0,
  P_L: 0,
  percentage_change: 0,
},
  PYPL: {
    symbol: "PYPL",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  MSFT: {
    symbol: "MSFT",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  ADBE: {
    symbol: "ADBE",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  AMD: {
    symbol: "AMD",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  CSCO: {
    symbol: "CSCO",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  PEP: {
    symbol: "PEP",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  INTU: {
    symbol: "INTU",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  SBUX: {
    symbol: "SBUX",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  HON: {
    symbol: "HON",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  TEAM: {
    symbol: "TEAM",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  FISV: {
    symbol: "FISV",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  ADI: {
    symbol: "ADI",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  QCOM: {
    symbol: "QCOM",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  SPLK: {
    symbol: "SPLK",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  CSX: {
    symbol: "CSX",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  ZM: {
    symbol: "ZM",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
  CTSH: {
    symbol: "CTSH",
    LTP: 0,
    P_L: 0,
    percentage_change: 0,
  },
};

module.exports = masterOBJ;
