var symbolToName = new Map();

symbolToName.set("TSLA","Tesla");
symbolToName.set("AAPL","Apple");
symbolToName.set("INTC", "Intel");
symbolToName.set("NFLX", "Netflix");
symbolToName.set("NVDA", "Nvidea");
symbolToName.set("META", "Facebook");
symbolToName.set("GOOGL", "Google");
symbolToName.set("AMZN","Amazon");
symbolToName.set("BINANCE:BTCUSDT", "Bitcoin");
symbolToName.set("PYPL", "Paypal");
symbolToName.set("MSFT", "Microsoft");
symbolToName.set("ADBE", "Adobe");
symbolToName.set("AMD", "Advanced Micro Devices");
symbolToName.set("CSCO", "Cisco");
symbolToName.set("PEP", "Pepsi");
symbolToName.set("INTU", "Intuit");
symbolToName.set("SBUX", "Starbucks");
symbolToName.set("HON", "Hon");
symbolToName.set("TEAM", "Atlassian");
symbolToName.set("FISV", "Fiserv");
symbolToName.set("ADI", "Analog Devices");
symbolToName.set("QCOM", "QUALCOMM");
symbolToName.set("SPLK", "Splunk");
symbolToName.set("CSX",  "Csx");
symbolToName.set("ZM", "Zoom");
symbolToName.set("CTSH", "Cognizant");

module.exports = symbolToName;